services:
  appify-mysql:
    image: mysql:8.0
    container_name: appify-mysql
    restart: always
    env_file: .env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u${DB_USER}", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - app-network

  appify-backend:
    build:
      context: ./backend
    container_name: appify-backend
    restart: unless-stopped
    env_file: .env
    ports:
      - "${PORT}:7050"
    volumes:
      - backend_uploads:/app/uploads
    depends_on:
      appify-mysql:
        condition: service_healthy
    networks:
      - app-network

  appify-client:
    build:
      context: ./client
    container_name: appify-client
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - appify-backend
    networks:
      - app-network

volumes:
  mysql_data:
  backend_uploads:

networks:
  app-network:
    driver: bridge
